43 add check for pr description (#44)
* added a step to check if PR has a link to issue, otherwise will not allow to continue further

* renamed first step

* added running also for PRs

* added running also for PRs

* added running also for PRs

* added running also for PRs

* added running also for PRs

* added running also for PRs

* added running also for PRs

---------

Co-authored-by: Alex Duzhev <alexey.duzhev@tmrw.com>

diff --git a/.github/workflows/preview-cd.yml b/.github/workflows/preview-cd.yml
--- a/.github/workflows/preview-cd.yml
+++ b/.github/workflows/preview-cd.yml
@@ -6,18 +6,31 @@ env:
   PROJECTS_ROOT: "itbalis-projects"
 
 on:
+  pull_request:
+    types: [opened, synchronize, reopened, edited]
   push:
     branches-ignore:
       - main
 
 jobs:
-  build-and-cache:
+  test-build-and-cache:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        node-version: [20]
     steps:
       - uses: actions/checkout@v4
+
+      - name: Check PR Description for Issue Link
+        if: github.event_name == 'pull_request'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          PR_BODY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .body)
+          if echo "$PR_BODY" | grep -q '#[0-9]\+'; then
+            echo "Pull request description contains a link to an issue."
+          else
+            echo ":name_badge: Pull request description must contain a link to an issue (e.g., #123)." >> $GITHUB_STEP_SUMMARY
+            echo "Error: Pull request description must contain a link to an issue (e.g., #123)." >&2
+            exit 1
+          fi
 
       - uses: pnpm/action-setup@v4
         with:
@@ -63,8 +76,9 @@ jobs:
             !**/.github/**
 
   deploy:
-    needs: build-and-cache
+    needs: test-build-and-cache
     runs-on: ubuntu-latest
+    if: github.event_name != 'pull_request'
     steps:
       - uses: actions/checkout@v4
 
@@ -99,7 +113,7 @@ jobs:
           INSPECT_URL=$(grep -oP 'Inspect: \K(https://[^\s]+)' vercel_output.txt || echo "Not Found")
           PREVIEW_URL=$(grep -oP 'Preview: \K(https://[^\s]+)' vercel_output.txt || echo "Not Found")
           echo "Preview deployed :rocket:" >> $GITHUB_STEP_SUMMARY
-          echo "Alias URL: $alias" >> $GITHUB_STEP_SUMMARY
+          echo ":white_check_mark: Alias URL: $alias" >> $GITHUB_STEP_SUMMARY
           echo "Tech links: =========================================================" >> $GITHUB_STEP_SUMMARY 
           echo "Inspect URL: $INSPECT_URL" >> $GITHUB_STEP_SUMMARY
           echo "Preview URL: $PREVIEW_URL" >> $GITHUB_STEP_SUMMARY
