add fixed names for vercel build preview. It will take name of brunch for prefix, like https://branch-name.shoplist-be.vercel.app
it should also override previous preview not to create thousands of them =)

diff --git a/.github/workflows/preview-cd.yml b/.github/workflows/preview-cd.yml
--- a/.github/workflows/preview-cd.yml
+++ b/.github/workflows/preview-cd.yml
@@ -1,11 +1,12 @@
-name: ci-prod
+name: CD Preview
+
 env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
 
 on:
-  pull_request:
-    branches:
+  push:
+    branches-ignore:
       - main
 
 jobs:
@@ -33,29 +34,32 @@ jobs:
       - name: Prettier check
         run: pnpm format
 
-  Deploy-to-Production:
+  Deploy-to-Preview:
     needs: Testing-step
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Install pnpm globally
         run: npm install -g pnpm
+
       - name: Install Vercel CLI
         run: npm install --global vercel@latest
       - name: Pull Vercel Environment Information
-        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
+        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+
       - name: Build Local Artefacts
-        run: pnpm install &&  pnpm build
+        run: pnpm install && pnpm build
       - name: Build Project Artifacts
-        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
+        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel and get Preview URL
         id: deploy
         run: |
-          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}  > vercel_output.txt 2>&1
+          DEPLOY_NAME=${GITHUB_REF#refs/heads/} 
+          vercel deploy --prebuilt --name=$DEPLOY_NAME --token=${{ secrets.VERCEL_TOKEN }} > vercel_output.txt 2>&1
       - name: Extract URLs and add to summary
         run: |
           INSPECT_URL=$(grep -oP 'Inspect: \K(https://[^\s]+)' vercel_output.txt || echo "Not Found")
-          PRODUCTION_URL=$(grep -oP 'Production: \K(https://[^\s]+)' vercel_output.txt || echo "Not Found")
-          echo "Production deployed :rocket:" >> $GITHUB_STEP_SUMMARY
+          PREVIEW_URL=$(grep -oP 'Preview: \K(https://[^\s]+)' vercel_output.txt || echo "Not Found")
+          echo "Preview deployed :rocket:" >> $GITHUB_STEP_SUMMARY
           echo "Inspect URL: $INSPECT_URL" >> $GITHUB_STEP_SUMMARY
-          echo "Production URL: https://shoplist-be.vercel.app" >> $GITHUB_STEP_SUMMARY
+          echo "Preview URL: $PREVIEW_URL" >> $GITHUB_STEP_SUMMARY
